##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - aptitude
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - git
    - ctk-doc-tools
    - intltool
    - libgirepository1.0-dev
    - libgirepository1.0-doc
    - libgladeui-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - meson
    - python-gi-dev
    - python3-dev
    - python3-gi
    - wget
    - xauth
    - xvfb

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 libctk-3-doc'

build_scripts:
  - ./before-build
  - ./make-scanbuild meson
  - ./after-build

after_scripts:
  - ./gen-index -l 20
